# detective-content-sha256: 2226986b95211aae8a3a25fdccc152d45192f5c99175417476a33e32014f77d4
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/resolve.py::connected_components.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.resolve import connected_components


@pytest.mark.detective
def test_connected_components_value_0():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = connected_components(sets=[{"x"}])
    assert result == [frozenset({"x"})]
    assert type(result[0]) is frozenset
