# detective-content-sha256: d5f082567736b4bf705ccd931983ed77cc875e51cc74de53c96ae222a9c3b721
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::structural_class.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import structural_class


@pytest.mark.detective
def test_structural_class_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = structural_class(aa="abc")
    assert result == "uncertain"
