# detective-content-sha256: 61944416765dbfc56548241ebca8ffc433de50865df47df42374786eb9cf9a0a
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/completeness.py::spec_completeness.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.completeness import spec_completeness


@pytest.mark.detective
def test_spec_completeness_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = spec_completeness(initial=2, survivors=2)
    assert result == (1.0, 1.0, 0.0)
