# detective-content-sha256: bb8df557795426b15c07b871cfe81cdb7a1f8a488d03c3bec9d46fa519f918ca
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/search.py::falsifiable.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.search import falsifiable


@pytest.mark.detective
def test_falsifiable_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = falsifiable(n_candidates_start=0, kappas=[1])
    assert result is False


@pytest.mark.detective
def test_falsifiable_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = falsifiable(n_candidates_start=2, kappas=[1])
    assert result is True
