# detective-content-sha256: a4aebe5b46cf6f54fb3e2f536772a6a2b70a3dd0e4f30e3d823bc648134b24fc
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/web.py::reverse_adjacency.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.web import Coupling, RelationalWeb, reverse_adjacency


@pytest.mark.detective
def test_reverse_adjacency_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reverse_adjacency(
        web=RelationalWeb(couplings=(Coupling(a="x", b="x", weight=1.0, direction=1),)),
        min_weight=1.0,
    )
    assert result == {"x": ["x"]}


@pytest.mark.detective
def test_reverse_adjacency_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reverse_adjacency(
        web=RelationalWeb(couplings=(Coupling(a="x", b="x", weight=1.0, direction=1),)),
        min_weight=2.5,
    )
    assert result == {"x": []}


@pytest.mark.detective
def test_reverse_adjacency_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = reverse_adjacency(
        web=RelationalWeb(
            couplings=(
                Coupling(a="source", b="A", weight=1.0, direction=1),
                Coupling(a="source", b="B", weight=1.0, direction=1),
                Coupling(a="decoy", b="A", weight=1.0, direction=1),
                Coupling(a="unrelated", b="X", weight=1.0, direction=1),
            )
        ),
        min_weight=0.0,
    )
    assert result == {
        "source": [],
        "A": ["decoy", "source"],
        "B": ["source"],
        "decoy": [],
        "unrelated": [],
        "X": ["unrelated"],
    }
