# detective-content-sha256: 30c1226cbde3504e7957258f1604e6036a5a21738e5aaff5a3d7a464cb1fa33c
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::quest_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import quest_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("H", ["A", "B"], "resolving"),
            "A resolving quest: H reaches across to A, B — a coherent distant cure.",
        ),
        (
            ("H", ["A", "B"], "entangling"),
            "An entangling quest: H couples A, B, but they never lock into a cure.",
        ),
        (
            ("H", ["A"], "indeterminate"),
            "An indeterminate quest: H touches A with no coherence axis to resolve.",
        ),
    ],
)
def test_quest_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert quest_clause(*args) == expected
