# detective-content-sha256: a1e70f31d2b419b61b7e02cdb0371bf01452ff7d8de4a163452b20f42d726d3a
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/metabolic.py::metabolic_pathways.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.metabolic import metabolic_pathways


@pytest.mark.detective
def test_metabolic_pathways_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = metabolic_pathways(relation_rows=[["x"]], root="abc")
    assert result == {"abc"}
