# detective-content-sha256: 9db8fb50250930297fc7abf392c9c11767b68130612956610009fd1a4ff5d077
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::tragedy_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import tragedy_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("TP53", "apoptosis", "doomed"),
            "A tragedy: TP53 drives an unstoppable cascade to a doomed sink at apoptosis.",
        ),
        (
            ("TP53", "apoptosis", "suppressed"),
            "A tragedy: TP53 drives apoptosis down into a suppressed, locked-off sink.",
        ),
        (
            ("TP53", "apoptosis", "indeterminate"),
            "An indeterminate arc from TP53 to apoptosis: its paths disagree, so no doom holds.",
        ),
    ],
)
def test_tragedy_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert tragedy_clause(*args) == expected
