# detective-content-sha256: d2fe98fdf4891d602f38eb86799acc90933c5d334cd359bbc6236c25416e65f9
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::outcome_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import outcome_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("A", "amplifies", "B", "confirmed"),
            "Your hypothesis that A amplifies B — the shadow confirms it.",
        ),
        (
            ("A", "amplifies", "B", "contradicted"),
            "Your hypothesis that A amplifies B — the shadow contradicts it; it falls out.",
        ),
        (
            ("A", "amplifies", "B", "standing"),
            "Your hypothesis that A amplifies B — untestable on this shadow (it stands, unjudged).",
        ),
    ],
)
def test_outcome_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert outcome_clause(*args) == expected
