# detective-content-sha256: 6f9b643d6cede0ec590e85bcc14a99a1e9f32706fe3c79ea7c6d6657cdf35979
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/reference_fetch.py::age_bucket.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.reference_fetch import age_bucket


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((1.0625,), "children"),
        ((1.0,), "children"),
        ((0.9,), "infant"),
        ((13.0,), "adolescent"),
        ((12.9,), "children"),
        ((18.0,), "adult"),
        ((17.9,), "adolescent"),
    ],
)
def test_age_bucket_golden(args, expected):
    """VALUE golden captures — pure + deterministic (7 inputs)."""
    assert age_bucket(*args) == expected
