# detective-content-sha256: a84ab2d24b82dcf857684030bfe8587327fafe7cc03d5574c178ea0e3616520e
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/consequence.py::consequence_similarity.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.consequence import consequence_similarity


@pytest.mark.detective
def test_consequence_similarity_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = consequence_similarity(a=(1.0,), b=(1.0,))
    assert result == 1.0
