# detective-content-sha256: f8053dff8bcf99d041380847082bd3982880ddc0f1c3c2a8ab3328c836c6716b
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/coexpression.py::cache_key.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.coexpression import cache_key


@pytest.mark.detective
def test_cache_key_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = cache_key(genes=["B", "A", "A"])
    assert result == "f2314439597c11e2"
