# detective-content-sha256: 3caa26f0379aa9c5af0d39843d6fbcf1a02e6612f89a0aebf4b871611c301f8b
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/meter.py::coherence_meter.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.meter import coherence_meter


@pytest.mark.detective
def test_coherence_meter_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = coherence_meter(confirmed=-1, contradicted=0, standing=1)
    assert result == 0.0


@pytest.mark.detective
def test_coherence_meter_value_1():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = coherence_meter(confirmed=-1, contradicted=-1, standing=-1)
    assert result == 0.0
    assert repr(result) == "0.0"


@pytest.mark.detective
def test_coherence_meter_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = coherence_meter(confirmed=0, contradicted=2, standing=-1)
    assert result == -0.8
