# detective-content-sha256: 96b7e3c3407cd51c2594ff12c5ea30c01742854a81251f070bc0051c50105a05
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/quest.py::quest_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.quest import quest_verdict


@pytest.mark.detective
def test_quest_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = quest_verdict(r=1.0625, min_coherence=1.0625, opinionated=1)
    assert result == "resolving"


@pytest.mark.detective
def test_quest_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = quest_verdict(r=-1.0, min_coherence=-1.0, opinionated=-1)
    assert result == "indeterminate"
