# detective-content-sha256: 3ab62424ab472ceb15d424e1fbaa04afd2ca52bd86f992d8becbc69d737c36fb
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::signature_compatibility.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import signature_compatibility


@pytest.mark.detective
def test_signature_compatibility_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = signature_compatibility(aa_a="abc", aa_b="abc", min_agree=1)
    assert result == "compatible"
