# detective-content-sha256: 68063f7f60867a6d4762f34972eb592b0b0ef882620c05eebd34e4944ea45732
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/driver.py::proximity_coherence.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.driver import proximity_coherence


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        ((["x"], {"x": ["x"]}), {"x": 1.0}),
        ((["x", "x"], {"x": ["x"]}), {"x": 1.0}),
    ],
)
def test_proximity_coherence_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert proximity_coherence(*args) == expected
