# detective-content-sha256: ec63785772ab9d4ae2960f2aa0b1998e0f42d24565b6aebac58cae0b9b0f5930
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::comedy_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import comedy_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("A", "B", "vicious"),
            "A vicious comedy: A and B lock into a mutual-regulation loop turned pathological.",
        ),
        (
            ("A", "B", "homeostatic"),
            "A homeostatic comedy: A and B hold each other in check — self-correcting.",
        ),
        (
            ("A", "B", "indeterminate"),
            "An indeterminate loop between A and B: the loop-gain sign does not settle.",
        ),
    ],
)
def test_comedy_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert comedy_clause(*args) == expected
