# detective-content-sha256: d005d853d9d23fe6bfb9318dcf89f85cc5546f7f239ff32750a7d4d896a34a36
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/web.py::induced_subweb.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.web import Coupling, RelationalWeb, induced_subweb


@pytest.mark.detective
def test_induced_subweb_value_0():
    """VALUE survivor — distinguishing witness (original raises TypeError: 'NoneType' object is not iterable) (confidence 0.95)."""
    try:
        _result = induced_subweb(
            web=RelationalWeb(couplings=(Coupling(a="x", b="x", weight=1.0, direction=1),)),
            keep=None,
        )
    except TypeError as _exc:
        assert str(_exc) == "'NoneType' object is not iterable"
    except BaseException as _exc:
        pytest.fail(f"expected TypeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected TypeError, but the call returned {_result!r}")


@pytest.mark.detective
def test_induced_subweb_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = induced_subweb(
        web=RelationalWeb(
            couplings=(
                Coupling(a="source", b="A", weight=1.0, direction=1),
                Coupling(a="unrelated", b="X", weight=1.0, direction=1),
            )
        ),
        keep={"A", "source"},
    )
    assert (
        repr(result)
        == "RelationalWeb(couplings=(Coupling(a='source', b='A', weight=1.0, direction=1),))"
    )
