# detective-content-sha256: 053229d8bad0aeaac40bb51d7f904ff7f1bc76256097e2dafde440d2cb619469
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/search.py::eliminate_two_sign.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.search import eliminate_two_sign


@pytest.mark.detective
def test_eliminate_two_sign_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = eliminate_two_sign(
        candidates=["a", "b", "c", "d"], constraints={"k1": ["b", "c"], "k2": ["d"]}, censors={}
    )
    assert (
        repr(result)
        == "Trajectory(steps=[Step(constraint='k1', kappa=2), Step(constraint='k2', kappa=1)], sigma=2, survivors_left=['a'], falsifiable=True, bottom=False)"
    )


@pytest.mark.detective
def test_eliminate_two_sign_value_1():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = eliminate_two_sign(candidates=["a", "b"], constraints={"k1": ["a", "b"]}, censors={})
    assert (
        repr(result)
        == "Trajectory(steps=[], sigma=None, survivors_left=['a', 'b'], falsifiable=False, bottom=False)"
    )


@pytest.mark.detective
def test_eliminate_two_sign_value_2():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = eliminate_two_sign(candidates=["x"], constraints={"x": ["x"]}, censors={"x": ["x"]})
    assert (
        repr(result)
        == "Trajectory(steps=[Step(constraint='x', kappa=1)], sigma=None, survivors_left=[], falsifiable=False, bottom=True)"
    )
