# detective-content-sha256: a11e76d0ca1e5110185a54ac3f55e54fd624593c0b7ccfeb12115516617f9950
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/l2_encoder.py::data_facts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.l2_encoder import data_facts


@pytest.mark.detective
def test_data_facts_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = data_facts(token="abc", diff_data=True, differentiated=True, coexpresses_seed=True)
    assert result == ["abc differentiates population", "abc tracks seed"]


@pytest.mark.detective
def test_data_facts_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = data_facts(token="", diff_data=False, differentiated=False, coexpresses_seed=False)
    assert result == [" lacks data"]
