# detective-content-sha256: f5678097dcace0dfd12c2318e4e1ddb60466304d96dd59e4118f548c5bb84883
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::feature_agreement.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import feature_agreement


@pytest.mark.detective
def test_feature_agreement_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = feature_agreement(diff=1.0625, tol_close=1.0625, tol_far=1.0625)
    assert result == "agree"
