# detective-content-sha256: fe3e6c26a7a704a8152d880f4d894268408b53d3f95792cf3ccba210622e7391
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/narrative.py::triples_to_contracts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.narrative import triples_to_contracts


@pytest.mark.detective
def test_triples_to_contracts_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = triples_to_contracts(triples=[("A", "harm", "B"), ("A", "seize", "C")])
    assert (
        result
        == '{"contract_version": "2.0", "predicate": {"args": [{"entity_id": "e0", "lemma": "A", "type_thread": []}, {"entity_id": "e1", "lemma": "B", "type_thread": []}], "features": {"verb": "harm", "verb_classes": ["harm"], "verb_thread": []}, "op": "EVENT"}}\n{"contract_version": "2.0", "predicate": {"args": [{"entity_id": "e0", "lemma": "A", "type_thread": []}, {"entity_id": "e2", "lemma": "C", "type_thread": []}], "features": {"verb": "seize", "verb_classes": ["seize"], "verb_thread": []}, "op": "EVENT"}}'
    )
