# detective-content-sha256: 4757be2b1297b2edad222bf66e7083a993a02867659885e9707fa77005167d5c
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/string.py::row_to_event.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.string import row_to_event


@pytest.mark.detective
def test_row_to_event_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = row_to_event(fields=["x"], alias={"x": "x"})
    assert result is None
