# detective-content-sha256: 01561c41bd734bf55dbff8701677b7bcdbacbcfc40b6ba23e479b157dbf1bfe4
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::lament_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import lament_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (
            ("dopamine", "tyramine", "substituted"),
            "Route around the lost dopamine: tyramine can hold its role.",
        ),
        (
            ("dopamine", None, "palliative"),
            "No stand-in for dopamine: recognize the loss and manage a structured decline.",
        ),
        (
            ("abc", "abc", "abc"),
            "No stand-in for abc: recognize the loss and manage a structured decline.",
        ),
    ],
)
def test_lament_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (3 inputs)."""
    assert lament_clause(*args) == expected
