# detective-content-sha256: 5290b00d60e400734e77347c253f18b04ea21aaa206c4f48ae8221d15b202f10
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/operator.py::edge_outcome.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.operator import edge_outcome


@pytest.mark.detective
def test_edge_outcome_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edge_outcome(subject_sign=-1, target_sign=-1, polarity=0)
    assert result == "contradicted"
