# detective-content-sha256: edb3075355d1156018897f3656f49e7dde89d2a08612a02ef5fbb51675920a8f
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/position.py::place.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.position import place


@pytest.mark.detective
def test_place_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = place(dimension="abc", value=1.0625, center=1.0625, spread=1.0625, k=1.0625, tier=1)
    assert (
        repr(result)
        == "Position(dimension='abc', sign=0, depth=0.0, zero=1.0625, tier=1, differential=Differential(kind='none', surprise=0.0, spread=1.0625))"
    )


@pytest.mark.detective
def test_place_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = place(dimension="", value=0.0, center=1.0, spread=2.5, k=1.0625, tier=-1)
    assert (
        repr(result)
        == "Position(dimension='', sign=0, depth=1.0, zero=1.0, tier=-1, differential=Differential(kind='none', surprise=0.4, spread=2.5))"
    )


@pytest.mark.detective
def test_place_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = place(dimension="", value=1.0, center=1.0625, spread=-1.0, k=2.5, tier=-1)
    assert (
        repr(result)
        == "Position(dimension='', sign=0, depth=0.0, zero=1.0625, tier=-1, differential=Differential(kind='none', surprise=0.0, spread=-1.0))"
    )


@pytest.mark.detective
def test_place_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = place(dimension="a", value=2.5, center=-1.0, spread=1.0, k=1.0625, tier=0)
    assert (
        repr(result)
        == "Position(dimension='a', sign=1, depth=3.5, zero=-1.0, tier=0, differential=Differential(kind='elevated', surprise=3.5, spread=1.0))"
    )
