# detective-content-sha256: d9a64b8c84d0dcf36ec9aca25c55e479ec8aa61e433b239f9a2a18af8efd9bc3
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/resolve.py::cluster_meter.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.resolve import cluster_meter


@pytest.mark.detective
def test_cluster_meter_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = cluster_meter(
        entities=frozenset({"A", "B", "C"}),
        signed_polar={"A": [("B", 1), ("C", 1)]},
        observed={"B": 1, "C": -1},
    )
    assert result == 0.2857142857142857
