# detective-content-sha256: 4b42c81e0720576673468736cf69307433295efacc8c189f800b51611179f2fa
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/coexpression.py::codeviation_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.coexpression import codeviation_verdict


@pytest.mark.detective
def test_codeviation_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = codeviation_verdict(n_codeviate=1, n_aligned=1, min_support=1, consistency=1.0)
    assert result == "co-varies"


@pytest.mark.detective
def test_codeviation_verdict_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = codeviation_verdict(n_codeviate=-1, n_aligned=-1, min_support=-1, consistency=-1.0)
    assert result == "insufficient"
