# detective-content-sha256: 1a95eb5bdae9f7c1389b14e0d63c999ab94f07f653b74ff6339cda9b65d94372
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/web.py::distances_to.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.web import distances_to


@pytest.mark.detective
def test_distances_to_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = distances_to(reverse_adj={"x": ["x"]}, target="abc")
    assert result == {"abc": 0}
