# detective-content-sha256: 596c46a8094fdcdf8083c1a9364be8457d4da4febdcc0e9d2f61642625772327
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/driver.py::rank_candidates.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.driver import rank_candidates


@pytest.mark.detective
def test_rank_candidates_value_0():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = rank_candidates(survivors=["x"], positive_kill_sets=[], n_observed=-1)
    assert result == [("x", 0.0)]
    assert repr(result[0][1]) == "0.0"
