# detective-content-sha256: ba6c0f6c0c31fe4bdbe562e41c8cfa5933c103f00b43e5ee5a191b39d66f11ee
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/clinic.py::observed_symptoms.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.clinic import observed_symptoms
from homeostat.position import Position


@pytest.mark.detective
def test_observed_symptoms_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = observed_symptoms(
        positions={
            "source": Position(dimension="source", sign=0, depth=0.0, zero=0.0),
            "B": Position(dimension="B", sign=1, depth=1.0, zero=0.0),
            "decoy": Position(dimension="decoy", sign=0, depth=0.0, zero=0.0),
            "A": Position(dimension="A", sign=1, depth=1.0, zero=0.0),
        }
    )
    assert result == ["A", "B"]
