# detective-content-sha256: e3951c62cd239c8d41a12a32737da8c0ab2d772976de31a010fe503210d25a78
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/l2_encoder.py::data_facts.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.l2_encoder import data_facts


@pytest.mark.detective
def test_data_facts_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = data_facts(token="abc", tier="abc", coexpresses_seed=True, binds_seed=True)
    assert result == ["abc tracks seed", "abc binds seed"]


@pytest.mark.detective
def test_data_facts_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = data_facts(token="", tier="nodata", coexpresses_seed=False, binds_seed=False)
    assert result == [" lacks data"]


@pytest.mark.detective
def test_data_facts_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = data_facts(token="", tier="dominant", coexpresses_seed=False, binds_seed=True)
    assert result == [" differentiates population", " dominates population", " binds seed"]


@pytest.mark.detective
def test_data_facts_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = data_facts(token="", tier="moderate", coexpresses_seed=False, binds_seed=False)
    assert result == [" differentiates population"]
