# detective-content-sha256: 9f7f9a59695c81e04aff6de54293a9d3cbf8dac30b545d75da95e82f0351360a
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/biophysics.py::bendability.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.biophysics import bendability


@pytest.mark.detective
def test_bendability_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = bendability(dna="abc")
    assert result is None
