# detective-content-sha256: 054ccc57867c11f942fd69fa1d48bf98d227fe1d089ca5fa938b72fda1c527ef
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/quest.py::order_parameter.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.quest import order_parameter


@pytest.mark.detective
def test_order_parameter_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = order_parameter(vectors=[(1.0, 1.0)])
    assert result == 1.4142135623730951
