# detective-content-sha256: d4b0fe22a29072b0e14d5fee501bc79ebd530e5df9077fab92d67ecbfc287c2c
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/differential.py::surprise.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.differential import surprise


@pytest.mark.detective
def test_surprise_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = surprise(value=1.0625, center=1.0625, spread=1.0625)
    assert result == 0.0


@pytest.mark.detective
def test_surprise_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = surprise(value=-1.0, center=1.0, spread=1.0625)
    assert result == 1.8823529411764706


@pytest.mark.detective
def test_surprise_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = surprise(value=-1.0, center=0.0, spread=1.0)
    assert result == 1.0


@pytest.mark.detective
def test_surprise_value_3():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = surprise(value=0.0, center=0.0, spread=-1.0)
    assert result == 0.0
    assert repr(result) == "0.0"


@pytest.mark.detective
def test_surprise_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = surprise(value=-1.0, center=-1.0, spread=0.0)
    assert result == 0.0
