# detective-content-sha256: 957ec9baff9f6a60d702d87dc743773f1aa087c8507f3ac72bcca8637e2a35f8
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/polarity.py::polarity_censors.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.polarity import polarity_censors


@pytest.mark.detective
def test_polarity_censors_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = polarity_censors(
        signed_adj={"A": [("B", 1)]}, candidates=["A"], observed={"B": 1, "Z": -1}
    )
    assert result == []
