# detective-content-sha256: 46214a62a520e70ad72c6cd49799f7c7f0b418eae8ba9cbd8aa4af09238b009d
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::tm_segments.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import tm_segments


@pytest.mark.detective
def test_tm_segments_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = tm_segments(aa="abc", window=3, threshold=0.0)
    assert result == 1
