# detective-content-sha256: 1349e319d5cc75f23b548e785ad303eea483bcb200446b0b8943eedc8e36ee13
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/position.py::mine_zero.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.position import mine_zero


@pytest.mark.detective
def test_mine_zero_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mine_zero(values=[])
    assert result is None
