# detective-content-sha256: 35857db1be0f98c84398aef953732548f542d8a11e6aeb8f17bf1f56be7c5581
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/string.py::edge_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.string import edge_disposition


@pytest.mark.detective
def test_edge_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edge_disposition(experimental=1, database=-1)
    assert result == "emit"


@pytest.mark.detective
def test_edge_disposition_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edge_disposition(experimental=-1, database=1)
    assert result == "emit"
