# detective-content-sha256: d3d9953bf8cdd67ecec99024b6a3295a11a85e474f237b7e5539fc01ba44ee38
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/resolve.py::complete_target_rank.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.resolve import complete_target_rank


@pytest.mark.detective
def test_complete_target_rank_value_0():
    """VALUE survivor — distinguishing witness (original raises TypeError: 'int' object is not iterable) (confidence 0.95)."""
    try:
        _result = complete_target_rank(ranked=[], target=-1)
    except TypeError as _exc:
        assert str(_exc) == "'int' object is not iterable"
    except BaseException as _exc:
        pytest.fail(f"expected TypeError, got {type(_exc).__name__}: {_exc!r}")
    else:
        pytest.fail(f"expected TypeError, but the call returned {_result!r}")
