# detective-content-sha256: 9a4c18d69095ab3ff648c456a59b326bfdcb09748e511638ffdef5b7efb763c1
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::exposure.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import exposure


@pytest.mark.detective
def test_exposure_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = exposure(aa="abc")
    assert result == "indeterminate"
