# detective-content-sha256: 89cac2c440d34a4339c4afbae77da4acb64037484517cbf36cd6d06156b154a2
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::compartment_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import compartment_verdict


@pytest.mark.detective
def test_compartment_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = compartment_verdict(exposure_a="membrane", exposure_b="indeterminate")
    assert result == "indeterminate"
