# detective-content-sha256: 6a649c826c3e0c4b2aa78e08425e3b6c4dcf802a18ca9507183b0392b818fbf9
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::verdict_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import verdict_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("RESOLVED", 1), "Resolved to a single mechanism — the structure explains this shadow."),
        (
            ("BOTTOM", 0),
            "Certified ⊥: no lawful mechanism in the relevant sources explains this shadow (a proof, not a failed search).",
        ),
        (
            ("DEGENERATE", 1),
            "Degenerate: the read is self-confirming — nothing was falsified (σ_sem = 0).",
        ),
        (("ASK", 3), "3 mechanisms fit this story equally; I cannot yet separate them."),
        (("ABSTAIN", 2), "Abstained: no available dimension separates the mechanisms that remain."),
    ],
)
def test_verdict_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (5 inputs)."""
    assert verdict_clause(*args) == expected
