# detective-content-sha256: 70aeb8b04d24167c274e8f48b0d154a489f345d8e04b7c36f02d30d4a25ce6d2
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/biophysics.py::yr_ry_balance.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.biophysics import yr_ry_balance


@pytest.mark.detective
def test_yr_ry_balance_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = yr_ry_balance(dna="abc")
    assert result is None
