# detective-content-sha256: 88c83f5c7a743d813727448c8ac30a2acd2a8eb74a44b66b35ae4133574fd7c6
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/clinic.py::is_certified.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.clinic import is_certified


@pytest.mark.detective
def test_is_certified_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = is_certified(verdict="abc", weakest="abc")
    assert result is False
