# detective-content-sha256: bffc540c75bb6553afa699f29491fb4d873941389fd3c3257ba0450a0b827d6f
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/differential.py::differential_kind.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.differential import differential_kind


@pytest.mark.detective
def test_differential_kind_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = differential_kind(value=1.0625, center=1.0625, spread=1.0625, k=1.0625)
    assert result == "none"


@pytest.mark.detective
def test_differential_kind_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = differential_kind(value=0.0, center=1.0, spread=2.5, k=1.0625)
    assert result == "none"


@pytest.mark.detective
def test_differential_kind_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = differential_kind(value=-1.0, center=1.0, spread=1.0625, k=0.0)
    assert result == "depleted"


@pytest.mark.detective
def test_differential_kind_value_3():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = differential_kind(value=0.0, center=2.5, spread=0.0, k=1.0)
    assert result == "none"


@pytest.mark.detective
def test_differential_kind_value_4():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = differential_kind(value=1.0, center=1.0625, spread=-1.0, k=2.5)
    assert result == "none"


@pytest.mark.detective
def test_differential_kind_value_5():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = differential_kind(value=2.5, center=-1.0, spread=1.0, k=1.0625)
    assert result == "elevated"
