# detective-content-sha256: 0bf49c83491510e9cc1a219a3403f3591511bae41b9d40af98aa0af67790c08f
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/ground.py::edit_within_1.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.ground import edit_within_1


@pytest.mark.detective
def test_edit_within_1_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edit_within_1(a="", b="a")
    assert result is True


@pytest.mark.detective
def test_edit_within_1_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = edit_within_1(a="", b="abc")
    assert result is False
