# detective-content-sha256: 0428b10227b0c3ce5fee4dff6c83f66e47948e522c9cd369073f2435036b6f31
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/search.py::entropy_bits.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.search import entropy_bits


@pytest.mark.detective
def test_entropy_bits_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = entropy_bits(n_survivors=2)
    assert result == 1.0
