# detective-content-sha256: e7aa05794580bd3c300e18adbe85e6a0a5b8df7c51e21613412ec82a1ef3f088
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/consequence.py::structural_consequence.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.consequence import structural_consequence


@pytest.mark.detective
def test_structural_consequence_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = structural_consequence(ref_aa="abc", var_aa="abc")
    assert result == (0.0, 0.0, 0.0, 0.0, 0.0)
