# detective-content-sha256: 5675d750ca34299035935650a947173867b5f72eb3f95ca478bcb501a7101a99
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::signature_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import signature_verdict


@pytest.mark.detective
def test_signature_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = signature_verdict(agreements=[], min_agree=-1)
    assert result == "compatible"
