# detective-content-sha256: 299d1a31c6760ab876960425c6d5efbe1054c69ef3ace0bb98ec0682f5883102
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/quest.py::part_vector.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.quest import part_vector


@pytest.mark.detective
def test_part_vector_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = part_vector(net_sign=1, depth=2, max_depth=3)
    assert result == (-0.5000000000000004, -0.8660254037844384)


@pytest.mark.detective
def test_part_vector_value_1():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = part_vector(net_sign=1, depth=1, max_depth=1)
    assert result == (1.0, -2.4492935982947064e-16)


@pytest.mark.detective
def test_part_vector_value_2():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = part_vector(net_sign=-1, depth=-1, max_depth=-1)
    assert result == (-1.0, 1.2246467991473532e-16)
