# detective-content-sha256: fb40f8dbdff8c6218da4b45e6156c30c358a9d146f689ad62161c891816b30ac
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/polarity.py::net_polarities.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.polarity import net_polarities


@pytest.mark.detective
def test_net_polarities_value_0():
    """VALUE survivor — distinguishing witness (equivalence search); outcomes ==-equal; distinction pinned by type/repr (confidence 0.95)."""
    result = net_polarities(signed_adj={"A": [("B", 1)], "B": [("C", -1)]}, source="A")
    assert result == {"A": 1, "B": 1, "C": -1}
    assert type(result["B"]) is int
    assert type(result["C"]) is int
