# detective-content-sha256: bbab4dc019d7f6f0e70d0cc5af5cf73e3616261a6390cb0cf72642b4181ee463
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/homology.py::homology_disposition.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.homology import homology_disposition


@pytest.mark.detective
def test_homology_disposition_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = homology_disposition(homology_type="", homology_species="homo_sapiens")
    assert result == "skip-ortholog"
