# detective-content-sha256: e6dfbc8c17f3d23677d3823ad73fc5fc3642d9b8ecce1e1ce1612046ef1d4fc3
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/event.py::couple_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.event import couple_verdict


@pytest.mark.detective
def test_couple_verdict_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = couple_verdict(support=1, censor=2)
    assert result == "killed"
