# detective-content-sha256: e37d9ba6643844d66b25f5badfa6718544997758a31602f18bdd805893511932
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::verdict_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import verdict_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("resolved", 1), "resolved to a single mechanism."),
        (("bottom", 0), "certified ⊥ — nothing in scope explains the presentation (a proof)."),
        (("degenerate", 1), "degenerate — self-confirming; nothing was falsified."),
        (("ask", 3), "3 candidate mechanisms fit; a measurement separates them."),
        (("abstain", 2), "2 candidate mechanisms fit; none yet separable."),
        (("abc", 1), "1 candidate mechanism fit; none yet separable."),
    ],
)
def test_verdict_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (6 inputs)."""
    assert verdict_clause(*args) == expected
