# detective-content-sha256: 1e91a8553db5f45377ce9dd72f281781226aa6b71a5c2c691653c755a3a193d1
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/structural.py::net_charge.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.structural import net_charge


@pytest.mark.detective
def test_net_charge_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = net_charge(aa="")
    assert result == 0.0
