# detective-content-sha256: 565d891c20cb328107d1ca13e2d3c68a2953f7a7fe3af805c92c482bcd78feb4
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/consequence.py::_delta.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.consequence import _delta


@pytest.mark.detective
def test__delta_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = _delta(ref_val=-1.0, var_val=0.0)
    assert result == 1.0
