# detective-content-sha256: eec5325279cf58801e95594d755ee45e6b52cbbb14d15604e95cbca33a28f3c4
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/loop.py::loop_verdict.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.loop import loop_verdict


@pytest.mark.detective
def test_loop_verdict_value_0():
    """VALUE survivor — distinguishing witness (equivalence search) (confidence 0.95)."""
    result = loop_verdict(
        resolved=False, falsifiable=False, grew=False, round_=2, max_rounds=-1, at_knee=False
    )
    assert result == "BUDGET"
