# detective-content-sha256: 68458c78c2f9d0d6fa0b0106f43eba0eceb9f9b63eaa90d902276a2b8fcd8325
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/render.py::allegory_clause.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.render import allegory_clause


@pytest.mark.detective
@pytest.mark.parametrize(
    "args, expected",
    [
        (("A", "B", "fungible", 2), "An allegory: A and B are role-fungible — 2 banks converge."),
        (
            ("A", "B", "coincidental", 1),
            "A resemblance between A and B that 1 bank(s) did not confirm as fungible.",
        ),
    ],
)
def test_allegory_clause_golden(args, expected):
    """VALUE golden captures — pure + deterministic (2 inputs)."""
    assert allegory_clause(*args) == expected
