# detective-content-sha256: 2cedb2bb3a545a5371ca9c3d0dcbde4028688f93042dd1d2920690ac5adc961f
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/web.py::reachers.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.web import reachers


@pytest.mark.detective
def test_reachers_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = reachers(reverse_adj={"a": ["b"], "b": ["c", "a"], "c": []}, target="a")
    assert result == {"c", "a", "b"}
