# detective-content-sha256: d658c537452982709f56f6cc40888d46982dd84ef6c5b7eb1c0f06ccd3587272
"""Auto-generated by Detective — warrant-classed tests for src/homeostat/differential.py::mine_spread.

Regenerated wholesale by `detective converge`; hand edits will be
overwritten. Witness lines carry full fidelity on purpose — for the
per-glob lint-ignore snippet see "Generated tests & lint" in
Detective's README."""

import pytest
from homeostat.differential import mine_spread


@pytest.mark.detective
def test_mine_spread_value_0():
    """VALUE survivor — golden capture (pure + deterministic) (confidence 0.9)."""
    result = mine_spread(values=[])
    assert result is None
